# Generated by Django 3.2 on 2022-06-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rental_limit',
            field=models.BooleanField(default=False, help_text='5冊以上借りたらTrue', verbose_name='貸出上限フラグ'),
        ),
    ]
