# Generated by Django 3.2 on 2022-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_rental_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_borrowing',
            field=models.BooleanField(default=False, help_text='本を借りていればTrue', verbose_name='本を借りている人/is_borrowing'),
        ),
    ]
