# Generated by Django 3.2 on 2022-06-23 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 23, 3, 59, 16, 672025, tzinfo=utc), verbose_name='書籍追加された日時'),
            preserve_default=False,
        ),
    ]
