# Generated by Django 3.2 on 2022-06-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_rental_app', '0002_books_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='borrower_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowing_books', to=settings.AUTH_USER_MODEL, verbose_name='本を借りた人'),
        ),
        migrations.AlterField(
            model_name='books',
            name='lender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lending_books', to=settings.AUTH_USER_MODEL, verbose_name='貸出許可を出した人'),
        ),
    ]
