# Generated by Django 3.2 on 2022-06-23 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental_app', '0004_alter_lendingstatus_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_rental_app.books', verbose_name='貸し出された書籍'),
        ),
    ]
