# Generated by Django 3.2 on 2022-06-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental_app', '0005_alter_lendingstatus_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingstatus',
            name='due_date',
            field=models.DateField(verbose_name='返却期限'),
        ),
    ]
