# Generated by Django 3.2 on 2022-06-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rental_app', '0006_alter_lendingstatus_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendingstatus',
            old_name='return_date',
            new_name='returned_date',
        ),
        migrations.RemoveField(
            model_name='lendingstatus',
            name='due_date',
        ),
    ]
